# Generated by Django 5.1.3 on 2024-12-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
